"""Add extraction and audit fields to documents

Revision ID: 33d7dcb2f7e4
Revises: 72a4b3a982ac
Create Date: 2026-06-30 12:29:28.046844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d7dcb2f7e4'
down_revision: Union[str, None] = '72a4b3a982ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('extracted_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('audit_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('audited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'audited_at')
    op.drop_column('documents', 'audit_report')
    op.drop_column('documents', 'extracted_at')
    op.drop_column('documents', 'extracted_data')
    # ### end Alembic commands ###
